target 'RestKITLibrary', :exclusive => true do
    pod "RestKITLibrary/GoogleGeocodingAPI", :path => "../"
    pod "RestKITLibrary/GooglePlacesAPI", :path => "../"
    pod "RestKITLibrary/RedmineAPI", :path => "../"
end

target 'Tests', :exclusive => true do
    pod "RestKITLibrary/GoogleGeocodingAPI", :path => "../"
    pod "RestKITLibrary/GooglePlacesAPI", :path => "../"
    pod "RestKITLibrary/RedmineAPI", :path => "../"
    #pod 'Specta', '~> 0.2.1'
    #pod 'Expecta'
    #pod 'FBSnapshotTestCase'
    #pod 'Expecta+Snapshots'
end
