target 'RestKITLibrary', :exclusive => true do
  pod "RestKITLibrary", :path => "../"
  pod "RestKITLibrary/GoogleGeocodingAPI", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RestKITLibrary", :path => "../"
  pod "RestKITLibrary/GoogleGeocodingAPI", :path => "../"
  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
